apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app
  namespace: ats-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      containers:
        - name: rag-container
          image: spandanx/wiki_rag:1.2
          ports:
            - containerPort: 8501
              name: rag-http-port